In [2]:
import pandas as pd
import numpy as np

In [17]:
df=pd.read_csv('movies.csv')

filter1=df['movieId']>1000
filter2=df['movieId']<2000

df[filter1&filter2]

,movieId,title,genres
807,1003,Extreme Measures (1996),Drama|Thriller
808,1004,"Glimmer Man, The (1996)",Action|Thriller
809,1005,D3: The Mighty Ducks (1996),Children|Comedy
810,1006,"Chamber, The (1996)",Drama
811,1007,"Apple Dumpling Gang, The (1975)",Children|Comedy|Western
812,1008,"Davy Crockett, King of the Wild Frontier (1955)",Adventure|Western
813,1009,Escape to Witch Mountain (1975),Adventure|Children|Fantasy
814,1010,"Love Bug, The (1969)",Children|Comedy
815,1011,Herbie Rides Again (1974),Children|Comedy|Fantasy|Romance
816,1012,Old Yeller (1957),Children|Drama
817,1013,"Parent Trap, The (1961)",Children|Comedy|Romance
818,1014,Pollyanna (1960),Children|Comedy|Drama
819,1015,Homeward Bound: The Incredible Journey (1993),Adventure|Children|Drama
820,1016,"Shaggy Dog, The (1959)",Children|Comedy
821,1017,Swiss Family Robinson (1960),Adventure|Children
822,1018,That Darn Cat! (1965),Children|Comedy|Mystery
823,1019,"20,000 Leagues Under the Sea (1954)",Adventure|Drama|Sci-Fi
824,1020,Cool Runnings (1993),Comedy
825,1021,Angels in the Outfield (1994),Children|Comedy
826,1022,Cinderella (1950),Animation|Children|Fantasy|Musical|Romance
827,1023,Winnie the Pooh and the Blustery Day (1968),Animation|Children|Musical
828,1024,"Three Caballeros, The (1945)",Animation|Children|Musical
829,1025,"Sword in the Stone, The (1963)",Animation|Children|Fantasy|Musical
830,1026,So Dear to My Heart (1949),Children|Drama
831,1027,Robin Hood: Prince of Thieves (1991),Adventure|Drama
832,1028,Mary Poppins (1964),Children|Comedy|Fantasy|Musical
833,1029,Dumbo (1941),Animation|Children|Drama|Musical
834,1030,Pete's Dragon (1977),Adventure|Animation|Children|Musical
835,1031,Bedknobs and Broomsticks (1971),Adventure|Children|Musical
836,1032,Alice in Wonderland (1951),Adventure|Animation|Children|Fantasy|Musical
...,...,...,...
1532,1970,"Nightmare on Elm Street 3: Dream Warriors, A (...",Horror|Thriller
1533,1971,"Nightmare on Elm Street 4: The Dream Master, A...",Horror|Thriller
1534,1972,"Nightmare on Elm Street 5: The Dream Child, A ...",Horror
1535,1973,Freddy's Dead: The Final Nightmare (Nightmare ...,Horror
1536,1974,Friday the 13th (1980),Horror|Mystery|Thriller
1537,1975,Friday the 13th Part 2 (1981),Horror
1538,1976,Friday the 13th Part 3: 3D (1982),Horror
1539,1977,Friday the 13th Part IV: The Final Chapter (1984),Horror
1540,1978,Friday the 13th Part V: A New Beginning (1985),Horror
1541,1979,Friday the 13th Part VI: Jason Lives (1986),Horror
1542,1980,Friday the 13th Part VII: The New Blood (1988),Horror
1543,1981,Friday the 13th Part VIII: Jason Takes Manhatt...,Horror
1544,1982,Halloween (1978),Horror
1545,1983,Halloween II (1981),Horror
1546,1984,Halloween III: Season of the Witch (1982),Horror
1547,1985,Halloween 4: The Return of Michael Myers (1988),Horror
1548,1986,Halloween 5: The Revenge of Michael Myers (1989),Horror
1549,1987,Prom Night (1980),Horror
1550,1988,Prom Night II (1987),Horror|Thriller
1551,1989,Prom Night III: The Last Kiss (1989),Horror
1552,1990,Prom Night IV: Deliver Us From Evil (1992),Horror
1553,1991,Child's Play (1988),Horror|Thriller
1554,1992,Child's Play 2 (1990),Horror|Thriller
1555,1993,Child's Play 3 (1991),Comedy|Horror|Thriller
1556,1994,Poltergeist (1982),Horror|Thriller
1557,1995,Poltergeist II: The Other Side (1986),Horror|Thriller
1558,1996,Poltergeist III (1988),Horror|Thriller
1559,1997,"Exorcist, The (1973)",Horror|Mystery
1560,1998,Exorcist II: The Heretic (1977),Horror
1561,1999,"Exorcist III, The (1990)",Horror

In [21]:



ishorror=df['genres'].str.contains('Horror')



horror_movie=df[ishorror]

print(horror_movie['movieId'].count())


# all comedy movie
"""iscomedy=df['genres'].str.contains('Comedy')
print(df[iscomedy]['title].head())

"""
""""print(df.head())




#df1=df.iloc[200:501]
#print(df1)

filter=((df['movieId']>200) & (df['movieId']<=500))



print(df[filter])
"""







"""
isresult=df.head()['movieId']==5
print(df.head()[isresult]['title'])
"""

877

"\nisresult=df.head()['movieId']==5\nprint(df.head()[isresult]['title'])\n"

In [24]:


dfratings=pd.read_csv('ratings.csv')


filter=dfratings['rating']==dfratings['rating'].max()

dfratings[filter]

       userId  movieId  rating   timestamp
21          2       17     5.0   835355681
22          2       39     5.0   835355604
29          2      150     5.0   835355395
37          2      222     5.0   835355840
44          2      265     5.0   835355697
45          2      266     5.0   835355586
83          2      551     5.0   835355767
85          2      585     5.0   835355817
89          2      589     5.0   835355697
90          2      590     5.0   835355395
91          2      592     5.0   835355395
101         3      318     5.0  1298862121
103         3      356     5.0  1298862167
113         3     1197     5.0  1298932770
130         3     2959     5.0  1298862874
133         3     3949     5.0  1298863174
148         4       34     5.0   949919556
149         4      112     5.0   949810582
150         4      141     5.0   949919681
154         4      260     5.0   949779042
156         4      296     5.0   949895708
158         4      349     5.0   949810582
159         4      356     5.0   949919763
160         4      357     5.0   949919681
161         4      364     5.0   949949538
171         4      480     5.0   949810582
172         4      541     5.0   949779091
173         4      588     5.0   949949486
174         4      589     5.0   949919938
176         4      594     5.0   949949538
...       ...      ...     ...         ...
99859     670       25     5.0   938782344
99863     670       47     5.0   938782050
99864     670       50     5.0   938781934
99867     670      318     5.0   938781934
99869     670      527     5.0   938782006
99871     670      593     5.0   938782234
99872     670      608     5.0   938782093
99873     670     1183     5.0   938782193
99883     670     2683     5.0   938782281
99885     670     2759     5.0   940943832
99888     670     2912     5.0   940943887
99889     671        1     5.0  1064891129
99893     671      260     5.0  1064891246
99895     671      318     5.0  1064890397
99896     671      356     5.0  1063503911
99901     671      551     5.0  1063503908
99903     671      589     5.0  1064891610
99908     671     1035     5.0  1065149492
99912     671     1136     5.0  1064891032
99913     671     1148     5.0  1064891021
99914     671     1196     5.0  1064890635
99916     671     1198     5.0  1064891024
99938     671     2291     5.0  1063500850
99950     671     2804     5.0  1064890525
99957     671     3114     5.0  1064891089
99975     671     4306     5.0  1064245548
99978     671     4886     5.0  1064245488
99979     671     4896     5.0  1065111996
99982     671     4993     5.0  1064245483
99994     671     5952     5.0  1063502716

[15095 rows x 4 columns]

In [61]:
minrate=dfratings['rating'].min()

ismin=dfratings['rating']==minrate
minmovieid=dfratings[ismin]['movieId']
minmovieid

466        1876
615        1358
984          70
1001        160
1053        355
1080        485
1101        588
1130        786
1279       1391
1338       1735
1429       2282
1447       2353
1474       2505
1480       2568
1617       3275
1647       3484
1890       5171
1899       5279
1905       5299
1929       5464
1947       5620
1979       6155
1980       6157
1984       6218
1988       6287
2019       6754
2060       7173
2067       7325
2074       7438
2108       8781
          ...
93773      1552
94142      3933
94167      4051
94182      4158
94199      4255
94227      4471
94266      4775
94302      5106
94318      5356
94357      5700
94404      6514
94474      8136
94475      8137
94476      8138
94478      8290
94777     82095
94830     87520
95188    125916
95198    129250
95280      3785
95531       780
95570      1917
95679     57368
95685       236
96042      3826
96345      8387
97581      1037
98536       593
98626       637
98649      4483
Name: movieId, Length: 1101, dtype: int64

In [24]:
import pandas as pd

d1={"Rollno":pd.Series([101,102,103,102,103]),"Name":pd.Series(['A','B','C','B','C'])}
df1=pd.DataFrame(d1)




"""

d2={"Rollno":pd.Series([103,101,102]),"Marks":pd.Series([100,200,300])}
df2=pd.DataFrame(d2)
print(df1)
print("---------------")
print(df2)

df=df1.join(df2.set_index('Rollno'),on='Rollno')
df

"""

  Name  Rollno
3    B     102
4    C     103

'\n\nd2={"Rollno":pd.Series([103,101,102]),"Marks":pd.Series([100,200,300])}\ndf2=pd.DataFrame(d2)\nprint(df1)\nprint("---------------")\nprint(df2)\n\ndf=df1.join(df2.set_index(\'Rollno\'),on=\'Rollno\')\ndf\n\n'

In [18]:







df=pd.read_csv('movies.csv')

dfratings=pd.read_csv('ratings.csv')


dfm=df.head()
dfm

dfr=dfratings.head()
#dfm ,dfr

dfresult=dfm.join(dfr.set_index('movieId'),on='movieId',lsuffix='__movie')




"""
#df.head()

df2=df[df.duplicated(keep=False)]

filter=dfresult['rating'].notnull()
notnullresult=dfresult[filter]
notnullresult

#filtered_df = dfresult[dfresult['rating'].notnull()]
#filtered_df
"""
print(dfresult)

   movieId                               title  \
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

                                        genres  userId  rating  timestamp
0  Adventure|Animation|Children|Comedy|Fantasy     NaN     NaN        NaN
1                   Adventure|Children|Fantasy     NaN     NaN        NaN
2                               Comedy|Romance     NaN     NaN        NaN
3                         Comedy|Drama|Romance     NaN     NaN        NaN
4                                       Comedy     NaN     NaN        NaN